### ISSUE TITLE
tool is showing failure, but portal shows success

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#55] opened 2021-02-19 17:51 UTC
My `cfde-submit status` is currently showing:

```
(cfdesubmit) (base) amandas-mbp-2:cfde-release amanda$ cfde-submit status
Running on service 'staging'
Running on service 'staging'

Status of CFDE Submission (Flow ID 70eb248c-b756-41f0-8edb-15a4a080c19d)
This instance ID: 1eb6b785-bc4b-4ea5-bff5-e7436aa733e0

This Flow has failed.
Current Flow Step: ErrorStateSubmission Flow failed: {
    "code": "FlowFailed",
    "description": "Error on state 'ErrorState': on input '{\"Error\": \"Lambda.Unknown\", \"Cause\": \"The cause could not be determined because Lambda did not return an error type. Returned payload: {\\\"errorMessage\\\":\\\"2021-02-19T17:32:38.453Z 9eb39e2a-a8a7-4293-ac1b-f7a2b3145ec3 Task timed out after 35.04 seconds\\\"}\"}'",
    "details": {
        "exception": "States.Runtime",
        "input": {
            "Cause": "The cause could not be determined because Lambda did not return an error type. Returned payload: {\"errorMessage\":\"2021-02-19T17:32:38.453Z 9eb39e2a-a8a7-4293-ac1b-f7a2b3145ec3 Task timed out after 35.04 seconds\"}",
            "Error": "Lambda.Unknown"
        },
        "state_name": "ErrorState"
    },
    "error": "FlowFailed",
    "time": "2021-02-19T17:32:38.476000+00:00"
}
```

According to the documentation, since I ran this without arguments, it should be telling me about my most recent submission.  However my most recent submission was metabolomics:
![image](https://user-images.githubusercontent.com/1719360/108541922-0f83b600-72b1-11eb-8061-c72d0b4a12c9.png)

and it is in the portal as ready for review:

![image](https://user-images.githubusercontent.com/1719360/108541986-1f02ff00-72b1-11eb-95ad-ada16af22f2c.png)

**Comment by NickolausDS** [comment] 2021-02-19 20:45
I noticed the same error on Dev a minute ago. I'm going to see if I can recreate this on staging and report back.

**Comment by NickolausDS** [comment] 2021-02-19 23:45
Amanda and I both submitted datasets to staging, and weren't able to recreate the error above. I'm not positive I know what the cause is, but I'll keep looking. It's possible one of the states on the flow has a timeout that is shorter than it should be.

**Comment by lliming** [comment] 2021-03-01 20:40
This issue is in the "In Progress" pipeline. Is it actively being worked on? Is it considered a blocker for the release this week?

**Comment by lliming** [comment] 2021-03-01 20:41
This issue is in the "In Progress" pipeline. Is it actively being worked on? Is it considered a blocker for this week's release?

**Comment by NickolausDS** [comment] 2021-03-01 21:00
This is a problem with the Automate email service and not the ingest action provider. I've talked with the Automate folks and they agreed to fix the problem, but I don't have an estimate on when that will be. 

I wasn't able to track down the exact cause of the problem above. It's possible it was one of two things -- a network timeout where the email service simply didn't respond in time, or alternatively input that should have been passed to the Email Service  didn't get sent and caused it to not respond in time. If the problem was the latter, it should have been fixed by https://github.com/nih-cfde/deriva-action-provider/pull/28.

On the question of this ticket status, I might consider this blocked on the Automate teams fix. However, I don't think it should be a blocker for this weeks release. So far, this has been the only recorded event of this happening to my knowledge.

**Comment by NickolausDS** [comment] 2021-03-02 19:45
I tracked down the cause of this, and it's been confirmed to be a timeout in the Email Service. The automate team will fix this so the Action will set this automate action to a 'failed' state. Instead of throwing an error, the flow will complete as it should. The result will be the user will not see an email, but will still be able to view a generic error message when running `cfde-submit status` along with some basic info they can send to us to track down the cause. 

We'll continue to watch for similar problems with the Email service, but so far this is the only time I know of this happening. Please post again if you see another similar message again! 

I'll move this to the backlog until Automate notifies us this has been fixed.

**Comment by DavidMichaelKelly** [comment] 2022-01-21 18:27
This issues seems to have been resolved by the automate team and hasn't reoccurred as far as I know

**Closed as completed by DavidMichaelKelly** 2022-01-21 18:27 UTC
Labels: Testing
